#!/usr/bin/env node
/**
 * Version + build number for one mobile app, kept in that app's version.json
 * (committed — the single source of truth). app.config.ts reads it, so
 * `expo prebuild` and Codemagic pick it up too.
 *
 * Run from the app folder (driver-app / operator-app), via its npm scripts:
 *
 *   npm run version:bump            build number +1           1.1.0 (101) → 1.1.0 (102)
 *   npm run version:bump -- patch   version + build number    1.1.0 (101) → 1.1.1 (102)
 *   npm run version:bump -- minor                             1.1.0 (101) → 1.2.0 (102)
 *   npm run version:bump -- major                             1.1.0 (101) → 2.0.0 (102)
 *   npm run version:sync            write version.json into ios/ as-is (no bump)
 *
 * ios/ is generated by `expo prebuild` and git-ignored, so an archive made in
 * Xcode only carries the new numbers if they are written into ios/ too — this
 * script does that (Info.plist + project.pbxproj) when ios/ exists. Without it
 * every Xcode upload went out as 1.0.0 (1).
 *
 * The build number never goes down and is shared by every upload of the app,
 * whatever the version: App Store Connect rejects a build number it has seen.
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const appDir = process.cwd();
const versionFile = path.join(appDir, 'version.json');
if (!fs.existsSync(versionFile)) {
  console.error(`No version.json in ${appDir} — run this from driver-app or operator-app.`);
  process.exit(1);
}

const [command = 'bump', part = 'build'] = process.argv.slice(2);
const current = JSON.parse(fs.readFileSync(versionFile, 'utf8'));
let { version, buildNumber } = current;

if (command === 'bump') {
  const [major, minor, patch] = version.split('.').map(Number);
  if (part === 'major') version = `${major + 1}.0.0`;
  else if (part === 'minor') version = `${major}.${minor + 1}.0`;
  else if (part === 'patch') version = `${major}.${minor}.${patch + 1}`;
  else if (part !== 'build') {
    console.error(`Unknown part "${part}" — use build, patch, minor or major.`);
    process.exit(1);
  }
  buildNumber += 1;
  fs.writeFileSync(versionFile, `${JSON.stringify({ version, buildNumber }, null, 2)}\n`);
  console.log(`${path.basename(appDir)}: ${current.version} (${current.buildNumber}) → ${version} (${buildNumber})`);
} else if (command !== 'sync') {
  console.error(`Unknown command "${command}" — use bump or sync.`);
  process.exit(1);
}

// ── Write the numbers into the generated iOS project, if there is one ──
const iosDir = path.join(appDir, 'ios');
const project = fs.existsSync(iosDir) && fs.readdirSync(iosDir).find((f) => f.endsWith('.xcodeproj'));
if (!project) {
  console.log('No ios/ project — `npx expo prebuild --platform ios` will pick the numbers up from version.json.');
  process.exit(0);
}
const target = path.basename(project, '.xcodeproj');

const plist = path.join(iosDir, target, 'Info.plist');
execFileSync('plutil', ['-replace', 'CFBundleShortVersionString', '-string', version, plist]);
execFileSync('plutil', ['-replace', 'CFBundleVersion', '-string', String(buildNumber), plist]);

const pbxproj = path.join(iosDir, project, 'project.pbxproj');
fs.writeFileSync(
  pbxproj,
  fs
    .readFileSync(pbxproj, 'utf8')
    .replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${version};`)
    .replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${buildNumber};`),
);

console.log(`ios/${target} now builds ${version} (${buildNumber}) — archive in Xcode as usual.`);
